# Generated by Django 2.1.7 on 2019-05-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(blank=True, choices=[('1', 'High'), ('2', 'Average'), ('3', 'Low')], default='A', max_length=1),
        ),
    ]
